# upstream php {
#   server unix:/tmp/php-cgi.socket;
#   server wordpress:9000;
# }

server {
    listen 80;

    root /var/www/html;

    index index.php index.html index.htm;

    location / {
            # try_files $uri $uri/ /index.php$is_args$args;
            try_files $uri $uri/ /index.php?$args; 
    }

    location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;

            fastcgi_buffer_size 128k;
            fastcgi_buffers 4 256k;
            fastcgi_busy_buffers_size 256k;
    }

    location ~ /\.ht {
            deny all;
    }

    location = /favicon.ico {
      log_not_found off; access_log off;
    }
    location = /robots.txt {
      log_not_found off; access_log off; allow all;
    }
    location ~* \.(css|gif|ico|jpeg|jpg|js|png|svg)$ {
      expires max;
      log_not_found off;
    }
}














